
export const JOBS_SEARCH_REQUEST = "JOBS_SEARCH_REQUEST"; 
export const JOBS_SEARCH_SUCCESS = "JOBS_SEARCH_SUCCESS"; 
export const JOBS_SEARCH_FAILURE = "JOBS_SEARCH_FAILURE"; 


export const SINGLE_JOBS_SEARCH_REQUEST = "SINGLE_JOBS_SEARCH_REQUEST"; 
export const SINGLE_JOBS_SEARCH_SUCCESS = "SINGLE_JOBS_SEARCH_SUCCESS"; 
export const SINGLE_JOBS_SEARCH_FAILURE = "SINGLE_JOBS_SEARCH_FAILURE"; 